### ISSUE TITLE
data/data.csv的格式與產生

### ISSUE THREAD

**Issue by faust690226** [yinguobing/tfrecord_utility#1]
版大,請問一下, split_data.ipynb裡面的data.csv是怎麼產生的,他的格式是怎麼樣呢？
![image](https://user-images.githubusercontent.com/39936662/46592706-e4d99e00-caf7-11e8-9f45-27fea7cd102f.png)

謝謝~

**Comment by quliulangle** [comment]
同问，请问这个data.csv是如何生成的呢

**Comment by yinguobing** [comment]
参考下ibug分支里的[这个文件](https://github.com/yinguobing/tfrecord_utility/blob/ibug/generate_csv.py)吧。

**Comment by yinguobing** [comment]
> 参考下ibug分支里的[这个文件](https://github.com/yinguobing/tfrecord_utility/blob/ibug/generate_csv.py)吧。

Sorry, 我仔细看了一下notebook，data的样式是这样的：

name | x | y
-- | -- | --
0.jpg | 262 | 117
1.jpg | 91 | 78
2.jpg | 107 | 77
3.jpg | 149 | 85
4.jpg | 157 | 87

所以，data.csv 与你要生成的tfrecord记录是对应的。也就是说格式不一定，要按照具体情况来设计。
