### ISSUE TITLE
Is this for segmentation task ?

### ISSUE THREAD

**Issue by jeffin07** [yinguobing/tfrecord_utility#5]
@yinguobing can you provide sample of the ".json" and "-pose.json" files. Because I don't understand what is the task this tf_record is used for. And if you're Planing for a different task (segmentation, classification, detection) tf_record utility I would like to contribute. Sorry if i asked something wrong

**Comment by yinguobing** [comment]
Hi @jeffin07 ,
Thanks for your advice and I just pushed sample json files in the data directory.

The tfrecord file generated from this repo is not for segmentation, classification or detection. It's a part of demonstration project showing deep learning beginners how to do facial landmark regression directly.

But feel free to fork this project for your own purpose, and you have not asked anything wrong. :smiley:

**Comment by jeffin07** [comment]
@yinguobing thanks for the JSON files  now it makes more sense
and I'm closing the issue

**Comment by wangping1408** [comment]
你好,我想问一下,我下载了你的Target数据,里面只有68个点的json文件,但是要生成tfrecord文件必须要有pose.json文件,我想问一下这个pose.json是如何生成的.
